### ISSUE TITLE
Not an issue but thank you

### ISSUE THREAD

**Issue by IdrisQe** [NyanMC/ArchitectBypass#1]
I'm glad to see that I'm not the only one who's really put off by this. I don't even know what it does honestly, but what it does doesn't matter, since the fact that this is so obfuscated is the problem. Like... imagine if a developer just hid an item in their mod that let specific users switch into creative mode, or automatically be added to the whitelist, in any server running their mod, intentionally hidden from server owners and modpack makers. There's so many ways this concept could be abused. Nevermind having a secret closed-source part of an open-source mod completely flies in the face of the entire point of open-sourcing.

Still won't be using EL myself, but thank you for bringing more attention to this.

**Comment by NyanMC** [comment]
yeah, it's the only mod i know that's decently popular that does something like this and the existence of the item pissed me off just enough to want to do something about it, since otherwise there is no way to equip this item
enigmatic lockbox (the closed source part you're referring to) was eventually merged with the main mod but i do agree that it's pretty shady that it even existed in the first place given it's a minecraft mod of all things

part of me does still wonder about the possibility to make a mod which bypasses all potential UUID-locked content from mod, but unfortunately i don't think such a thing is possible without breaking fundamental vanilla code or cases where people use UUIDs for their intended purpose

...i actually didn't know what to say here, i didn't want to just close this issue without a comment as i didn't want to look like i was being rude or ignoring what you said, but seeing people agree with me about how enigmatic legacy's UUID-locked content is stupid means a lot to me

**Comment by IdrisQe** [comment]
No need to worry about responding! I was just glad to see that this is still a sentiment people have about EL. It's nice to know it's been merged with the rest of the mod, but it's still... Not good in terms of implementation or transparency. But yeah, thanks again! 

Honestly I love "petty" mods like this that fix very specific things about other mods. I was considering making my own for a long time to fix Tetra because the dev for some reason absolutely refuses to add accessibility by improving the ridiuclously-tiny text and graphic sizes in the UI, every time (and there have been several times) that it's asked about, he just responds with "use the vanilla GUI size slider" or "won't fix" despite the fact that his text is HALF the size of the vanilla text, so you need to play on double your lowest comfortable UI size to be able to read anything properly, at which point every other UI in the game is way too large. Some day I might get around to it.

ANYWAY that was a pointless ramble, sorry about that! Just saying I really get where you're coming from with this.

**Comment by NyanMC** [comment]
that thing with tetra does sound really annoying actually, i never really thought about it myself when using the mod but i can definitely see how it's an issue (though i'm not sure how you would fix it without upscaling or reworking the entire gui)

i've definitely been tempted to make more "petty" mods like this one, and if i weren't burdened by the limitation known as "having better uses for my time" i would probably make mods to:
- perform dark magic to force scaling health to use a serverconfig (there is literally no reason for it to be done via datapack)
- make the thin air mod play nice with the artifacts snorkel
- completely revert all of the post-1.18 changes to baubley heart canisters because i hate them all
- make the warden completely and utterly unkillable without god tools or commands because i hate how many mods treat them as "the third boss of minecraft"
- add a prompt for how to open the inventory profiles next config, as the only fucking place in the entire mod that hints that the menu even exists is an easily missable line in the mod description
- many, many more which don't immediately come to mind

**Comment by IdrisQe** [comment]
> that thing with tetra does sound really annoying actually, i never really thought about it myself when using the mod but i can definitely see how it's an issue (though i'm not sure how you would fix it without upscaling or reworking the entire gui)
> 
> i've definitely been tempted to make more "petty" mods like this one, and if i weren't burdened by the limitation known as "having better uses for my time" i would probably make mods to:
> 
>     * perform dark magic to force scaling health to use a serverconfig (there is literally no reason for it to be done via datapack)
> 
>     * make the thin air mod play nice with the artifacts snorkel
> 
>     * completely revert all of the post-1.18 changes to baubley heart canisters because i hate them all
> 
>     * make the warden completely and utterly unkillable without god tools or commands because i hate how many mods treat them as "the third boss of minecraft"
> 
>     * add a prompt for how to open the inventory profiles next config, as the only fucking place in the entire mod that hints that the menu even exists is an easily missable line in the mod description
> 
>     * many, many more which don't immediately come to mind

IPN's config can at least be accessed via the mod menu, I think, so that's something at least?

But gosh, I haven't used many of these mods at all, or in a while (what did they do to Heart Canisters?), so I can't give my own experiences with them, but that said, _a datapack for configuration? WHY?!_ It's been a pain in the ass for me that basically every structure or mob mod now needs datapacks to configure stuff like spawnrates when they used to just be in the config files, I can't imagine using datapacks for something as logistically simple as Scaling Health.

That said, I would go with a common config instead - that's something I would change about EVERY mod, putting the server configs back in with the other configs instead of the stupid serverconfigs folder in every world. Generally if I'm making a server, I want to be able to test it in singleplayer too, which means duplicating all my serverconfig files. Or heaven forbid if I don't like the world I get when I first generate the server, and remake it but forget to pull the configured files out first.

The Warden topic is such a mood. We're currently playing a modpack with Apotheosis and _oh boy_ there are so many things that are unconfigurable that I would change about that mod, and it overwrites and breaks SO MANY other mods it's ridiculous, nevermind completely overwriting numerous vanilla items for no apparent reason. One thing that bothers me is that for a late-game enchanting setup, we'll need to kill _multiple_ Wardens. Yippee.

I guess the best we can do without a whole lot of time on our hands is to suggest things to the developers of respective mods though. A lot of mod authors probably already get annoyed at me with how much I'll suggest features or tweaks or configuration, sometimes for things I wouldn't even use myself, just because I think it would be useful >.>;;

**Comment by NyanMC** [comment]
there's more i would say about this but i don't want to keep replying on an issue thread, if you want to discuss this more feel free to contact me on discord by either joining my (very empty) [discord server](https://discord.com/invite/apVvEGphr9) or though dms (my userame there is @chromanyan, if we don't have any mutual servers you would need to friend request me)

one thing i will say here though, for the serverconfig thing i recommend the [night config fixes](https://modrinth.com/mod/night-config-fixes) mod, which on newer versions contains a config option that, when enabled, forces server configs to be read from the config folder like any other config for consistency
